name: Mirror to GitLab

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - beta
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Aster1630/Before-Its-Gone.git"
          git push gitlab HEAD:${{ github.ref_name }} --force
